version: "3.3"

services:

  postgres-server:
    image: postgres:10.1
    ports:
      - "10005:10005"  #mudar as portas
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZbX420Server
      TZ: America/Recife
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix:zabbix_4.2.8_v1 
    #zabbix/zabbix-server-pgsql:ubuntu-4.2-latest
    #build:
    ports:
      - "10051:10051"#mudar as portas
      - "10001:8080"#mudar as portas
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZbX420Server      
      ZBX_STARTPOLLERS: 10 #Quantidade de processos pré-alocados dos pollers 
      ZBX_STARTPINGERS: 10 #Quantidade de processos pré-alocados dos ICMP pingers - 1
      ZBX_STARTTRAPPERS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 5 #Quantidade de processos pré-alocados dos pollers de hosts indisponíveis - 1
      ZBX_STARTDISCOVERERS: 5 #qtd de processo pré-alocados para o discovery - 1
      ZBX_TIMEOUT: 30 #tempo máximo para o zbx aguardar um dado do agente
      ZBX_SENDERFREQUENCY: 20 #tempo para o enviar alertas pendentes - 30
      ZBX_STARTDBSYNCERS: 2 #Quantidade de processos pré-alocados dos DB Syncers -4
      ZBX_CACHESIZE: 500M
      ZBX_HISTORYCACHESIZE: 500M
      ZBX_TRENDCACHESIZE: 500M
      ZBX_HOUSEKEEPINGFREQUENCY: 6 #Intervalo entre execuções do processo de limpeza de dados (housekeeping) (em horas) - 6 
      ZBX_DEBUGLEVEL: 3
      TZ: America/Recife
    depends_on:
      - postgres-server
    volumes:
      - alertscripts:/usr/lib/zabbix/alertscripts
      - externalscripts:/usr/lib/zabbix/externalscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.2-latest
    ports:
      - "10002:80"    #mudar as portas
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZbX420Server 
      ZBX_SERVER_NAME: -ZBX- #substituir aqui 
      TZ: America/Recife
      PHP_TZ: America/Recife

  grafana:
    image: grafana/grafana:7.0.0
    ports:
      - "10000:3000"#mudar mudar as portas
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel 
      GF_SECURITY_ADMIN_PASSWORD: 420420
      GF_USERS_DEFAULT_THEME: light
      TZ: America/Recife
    volumes:
      - grafana:/var/lib/grafana


volumes:
  pgdata:
  alertscripts:
  externalscripts:
  grafana:
