version: "3.3"

services:

  postgres-server:
    image: postgres:11.3-alpine                             # Modificar de acordo com a versão desejada
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: l0g1c2515
      TZ: America/Recife
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
          
    build:
      context: /root/
      dockerfile: Dockerfile                                # Dockerfile de dependências do Zabbix-Server
    restart: always
    container_name: zabbix-server
    ports:
      - "10051:10051"
      - "80:8080"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: l0g1c2515      
      ZBX_STARTPOLLERS: 20                                  # Quantidade de processos pré-alocados dos pollers 
      ZBX_STARTPINGERS: 20                                  # Quantidade de processos pré-alocados dos ICMP pingers - 1
      ZBX_STARTTRAPPERS: 20
      ZBX_STARTPOLLERSUNREACHABLE: 20                       # Quantidade de processos pré-alocados dos pollers de hosts indisponíveis - 1
      ZBX_STARTDISCOVERERS: 15                              # Quantidade de processo pré-alocados para o discovery - 1
      ZBX_TIMEOUT: 20                                       # Tempo máximo para o zbx aguardar um dado do agente
      ZBX_SENDERFREQUENCY: 30                               # Tempo para o enviar alertas pendentes - 30
      ZBX_STARTDBSYNCERS: 2                                 # Quantidade de processos pré-alocados dos DB Syncers -4
      ZBX_CACHESIZE: 500M
      ZBX_HISTORYCACHESIZE: 500M
      ZBX_TRENDCACHESIZE: 500M
      ZBX_HOUSEKEEPINGFREQUENCY: 24                         # Intervalo entre execuções do processo de limpeza de dados (housekeeping) (em horas) - 6 
      ZBX_DEBUGLEVEL: 3
      TZ: America/Recife
    depends_on:
      - postgres-server
    volumes:
      - alertscripts:/usr/lib/zabbix/alertscripts
      - externalscripts:/usr/lib/zabbix/externalscripts

  zabbix-web: 
    image: zabbix/zabbix-web-nginx-pgsql:alpine-4.2.5       # Modificar de acordo com a versão e imagem desejada
    container_name: zabbix-web
    restart: always
    ports:
      - "8080:80"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: l0g1c2515
      ZBX_SERVER_NAME: “Nome do Servidor a ser monitorado”  # Informar o nome do novo Servidor
      TZ: America/Recife
      PHP_TZ: America/Recife

  grafana-server:
    image: grafana/grafana:6.2.2                           # Modificar de acordo com a versão desejada
    container_name: zabbix-grafana
    restart: always
    ports:
      - "3000:3000"
    user: "104:104"
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel
      GF_SECURITY_ADMIN_PASSWORD: logica51573m25
      GF_USERS_DEFAULT_THEME: light
      TZ: America/Recife
    volumes:
      - grafana:/var/lib/grafana


volumes:
  pgdata:
  alertscripts:
  externalscripts:
  grafana:
