version: "3.3"

services:

  postgres-server:
    image: postgres:10.1                                   # Modificar de acordo com a versão desejada
    ports:
      - "10005:10005"                                      # Caso necessário alterar as portas
    environment:
      POSTGRES_DB: zabbix                                  # Nome do banco de dados Zabbix
      POSTGRES_USER: zabbix                                # Usuário do banco de dados Zabbix
      POSTGRES_PASSWORD: Password                          # Senha do banco de dados Zabbix
      TZ: America/Recife
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
    build:
      context: /home/
      dockerfile: Dockerfile                                # Dockerfile de dependências do Zabbix-Server
    ports:
      - "10051:10051"                                       # Caso necessário alterar as portas
      - "10001:10002"                                       # Caso necessário alterar as portas
    environment:
      POSTGRES_USER: zabbix                                 # Usuário do banco de dados Zabbix
      POSTGRES_PASSWORD: Password                           # Senha do banco de dados Zabbix
      ZBX_STARTPOLLERS: 100                                 # Quantidade de processos pré-alocados dos pollers 
      ZBX_STARTPINGERS: 100                                 # Quantidade de processos pré-alocados dos ICMP pingers - 1
      ZBX_STARTTRAPPERS: 100
      ZBX_STARTPOLLERSUNREACHABLE: 50                       # Quantidade de processos pré-alocados dos pollers de hosts indisponíveis - 1
      ZBX_STARTDISCOVERERS: 15                              # Quantidade de processo pré-alocados para o discovery - 1
      ZBX_TIMEOUT: 30                                       # Tempo máximo para o zbx aguardar um dado do agente
      ZBX_SENDERFREQUENCY: 20                               # Tempo para o enviar alertas pendentes - 30
      ZBX_STARTDBSYNCERS: 2                                 # Quantidade de processos pré-alocados dos DB Syncers -4
      ZBX_CACHESIZE: 500M
      ZBX_HISTORYCACHESIZE: 500M
      ZBX_TRENDCACHESIZE: 500M
      ZBX_HOUSEKEEPINGFREQUENCY: 6                          # Intervalo entre execuções do processo de limpeza de dados (housekeeping) (em horas) - 6 
      ZBX_DEBUGLEVEL: 3
      TZ: America/Recife
    depends_on:
      - postgres-server
    volumes:
      - alertscripts:/usr/lib/zabbix/alertscripts
      - externalscripts:/usr/lib/zabbix/externalscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest  # Modificar de acordo com a versão desejada
    ports:
      - "10002:10001"                                       # Caso necessário alterar as portas
    environment:
      POSTGRES_USER: zabbix                                 # Usuário do banco de dados Zabbix
      POSTGRES_PASSWORD: Password                           # Senha do banco de dados Zabbix
      ZBX_SERVER_NAME: "Server_Name"                        # Substituir para o nome do servidor ZBX 
      TZ: America/Recife
      PHP_TZ: America/Recife

  grafana:
    image: grafana/grafana:6.2.2                            # Modificar de acordo com a versão desejada
    ports:
      - "10000:10000"                                       # Caso necessário alterar as portas
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel 
      GF_SECURITY_ADMIN_PASSWORD: Password                  # Senha de acesso ao usuário admin do Grafana
      GF_USERS_DEFAULT_THEME: light
      TZ: America/Recife
    volumes:
      - grafana:/var/lib/grafana

volumes:
  pgdata:
  alertscripts:
  externalscripts:
  grafana:
