FROM zabbix/zabbix-server-pgsql:ubuntu-latest 
USER root
RUN apt-get update
RUN ln -fs /usr/share/zoneinfo/America/Recife /etc/localtime
RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata 
RUN apt-get update && apt-get upgrade -y
RUN apt-get install vim -y
RUN apt-get snmpd snmp libsnmp-dev -y 
RUN apt-get php-snmp php php-fpm php-opcache -y 
RUN apt-get python3 python3-pip net-tools -y
RUN pip3 install pyTelegramBotAPI -y
