version: '3.8'

networks:
  network-zabbix:
    driver: bridge
    ipam:
        config:
            - subnet: 172.18.0.0/24
              gateway: 172.18.0.1

services:
  postgres-server:                                              # The Postgres Database Service
    image: postgres:latest                                      # Container image
    networks:
     - network-zabbix
    restart: always
    environment:                                                # Username, password and database name variables
      POSTGRES_USER: zabbix                                     # Database user
      POSTGRES_PASSWORD: zabbix                                 # Database password
      POSTGRES_DB: zabbix                                       # Database name
      PG_DATA: /var/lib/postgresql/data/pgdata                  # Data storage
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data

  zabbix-server:                                                # The Zabbix Server Service
    container_name: zabbix-server
    build:
      context: ./Dockerfile                                     # Adjust as per location of Dockerfile-server file
      dockerfile: Dockerfile-server 
    networks:   
      - network-zabbix
    links:
      - postgres-server
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - alertscripts:/usr/lib/zabbix/alertscripts
      - externalscripts:/usr/lib/zabbix/externalscripts
    environment:
      POSTGRES_USER: zabbix                                     # Database user
      POSTGRES_PASSWORD: zabbix                                 # Database password
      POSTGRES_DB: zabbix                                       # Database name
      ZBX_SERVER_NAME: zabbix-server                            # Zabbix Server name
      PHP_TZ: America/Recife                                    # Defining time zone
      ZBX_CACHESIZE: 400M                                       # Maximum disk cache size to store collected data. Increasing the value of this variable can improve Zabbix performance, but it can also increase disk space usage
      ZBX_HISTORYCACHESIZE: 50M                                 # This cache is used to store historical data collected by Zabbix agents and is used to speed up access to this data.
      ZBX_HOUSEKEEPINGFREQUENCY: 6                              # Defines how often database cleanup tasks are run. These tasks include removing old historical data, deleting resolved events, and compacting database tables.
      ZBX_TRENDCACHESIZE: 50M                                   # Cache used to store trend data collected by Zabbix agents and is used to speed up access to this data.
      ZBX_NODEADDRESS: 172.18.0.1:10051
    depends_on:
      - postgres-server

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-latest
    networks:
      - network-zabbix
    links:
      - postgres-server
    restart: always
    ports:
      - '80:8080'                                                # By default Zabbix Web uses port 80, if necessary it can be changed. Example 8080:8080 - external-port:internal-port
      - '443:8443'
    environment:
      POSTGRES_USER: zabbix                                      # Database user
      POSTGRES_PASSWORD: zabbix                                  # Database password
      POSTGRES_DB: zabbix                                        # Database name
      PHP_TZ: America/Recife                                     # Defining time zone
    depends_on:
      - postgres-server

  zabbix-agent:
    container_name: zabbix-agent
    build:
      context: ./Dockerfile                                      # Adjust as per location of Dockerfile-server file
      dockerfile: Dockerfile-agent
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
      - ./etc/zabbix/externalscripts:/etc/zabbix/externalscripts
      - ./etc/zabbix/alertscripts:/etc/zabbix/alertscripts
      - ./etc/zabbix/zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1
      - ZBX_USERPARAMETER=custom.vfs.dev.discovery[*],/etc/zabbix/externalscripts/queryDisks.pl  

  grafana:
    container_name: grafana-server
    image: grafana/grafana:latest-ubuntu                         # Modify according to the desired image version
    networks:
      - network-zabbix
    ports:
      - '3000:3000'                                              # By default Grafana uses port 3000, if necessary it can be changed. Example 3030:3000 - external-port:internal-port 
    restart: always
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel,yesoreyeram-boomtable-panel,grafana-worldmap-panel,grafana-clock-panel,yesoreyeram-boomtheme-panel,briangann-gauge-panel,agenty-flowcharting-panel
      GF_SECURITY_ADMIN_PASSWORD: Grafana                        # Grafana admin user access password
      GF_USERS_DEFAULT_THEME: dark                               # Defining Grafana theme
      TZ: America/Recife                                         # Defining time zone
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

volumes:
  pgdata:
  alertscripts:
  externalscripts:
  grafana:
