FROM zabbix/zabbix-agent2:ubuntu-latest 
USER root
RUN apt-get update
RUN ln -fs /usr/share/zoneinfo/America/Recife /etc/localtime
RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata 
RUN apt-get install vim snmpd snmp libsnmp-dev php-snmp php php-fpm php-opcache python3 python3-pip net-tools -y
RUN apt-get update && apt-get upgrade -y
RUN pip3 install pyTelegramBotAPI
