version: '3.8'

networks:
  network-zabbix-agent:
    driver: bridge
    ipam:
        config:
            - subnet: 172.20.0.0/24
              gateway: 172.20.0.1

services:              
  zabbix-agent:
    container_name: zabbix-agent-NoteLenovo
    build:
      context: ./                                      # Adjust as per location of Dockerfile-server file
      dockerfile: Dockerfile-agent
    user: root
    networks:
      - network-zabbix-agent
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME="Host Name"
      - ZBX_SERVER_HOST="IP Zabbix Server"
